# local-development.yml
# - all ports are exposed using host mapping
# - riak container is included for development (normally it would be elsewhere)

version: "3.9"
services:
  database:
    image: postgres:14
    container_name: database
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./pg_data/data:${PGDATA:-/var/lib/postgresql/data}
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR:-/var/log/postgresql}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=postgres

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django
    depends_on:
      - database
      - neo4j
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    environment:
      - UWSGI_UID=${UWSGI_UID:-1000}
      - UWSGI_GID=${UWSGI_GID:-1000}

  nginx:
    image: nginx:1
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS_DIR:-./ssl}:/etc/ssl:ro

  neo4j:
    image: rencinrig/neo4j-apoc:3.5.0
    container_name: neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    ports:
      - "7474:7474" # for HTTP
      - "7473:7473" # for HTTPS
      - "7687:7687" # for Bolt
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-./neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}
      - ${NEO4J_IMPORTS_PATH_HOST:-./neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}
      - ${NEO4J_LOGS_PATH_HOST:-./neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/fullchain.pem:/ssl/neo4j.cert:ro # SSL development certificate
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/privkey.pem:/ssl/neo4j.key:ro # SSL development key
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}

  safe:
    image: rencinrig/safe-server:1.0.1
    container_name: safe
    restart: on-failure
    ports:
      - ${SAFE_SERVER_PORT:-7777}:7777
    environment:
      - RIAK_IP=${RIAK_IP:-riak}
      - SLANG_SCRIPT=${SLANG_SCRIPT:-impact/mvp-ns.slang}
      - AKKA_LOG_LEVEL=${AKKA_LOG_LEVEL:-info}
    volumes:
      - ${SAFE_IMPORTS:-./safe/imports}:/imports
      - ${SAFE_PRINCIPAL_KEYS:-./safe/keys}:/principalkeys

  riak:
    image: rencinrig/riak-for-safe:latest
    container_name: riak
    restart: on-failure
    ports:
      - "8098:8098"
      - "8087:8087"
    volumes:
      - ./riak/data:/data
      - ./riak/config:/imports
