# production.yml
# - ports 80 and 443 are exposed using host mapping
# - riak is expected to be located on its own for all SAFE instances to connect to

version: '3.9'
services:

  database:
    image: postgres:14
    container_name: database
    volumes:
      - ./pg_data/data:${PGDATA:-/var/lib/postgresql/data}
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR:-/var/log/postgresql}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=postgres

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django
    depends_on:
      - database
      - neo4j
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    environment:
      - UWSGI_UID=${UWSGI_UID:-1000}
      - UWSGI_GID=${UWSGI_GID:-1000}

  nginx:
    image: nginx:1
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS_DIR:-./ssl}:/etc/ssl:ro

  neo4j:
    image: rencinrig/neo4j-apoc:3.5.0
    container_name: neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-./neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}
      - ${NEO4J_IMPORTS_PATH_HOST:-./neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}
      - ${NEO4J_LOGS_PATH_HOST:-./neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/fullchain.pem:/ssl/neo4j.cert:ro  # SSL development certificate
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/privkey.pem:/ssl/neo4j.key:ro     # SSL development key
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}

  safe:
    image: rencinrig/safe-server:1.0.1
    container_name: safe
    restart: on-failure
    environment:
      - RIAK_IP=${RIAK_IP:-riak}
      - SLANG_SCRIPT=${SLANG_SCRIPT:-impact/mvp-ns.slang}
      - AKKA_LOG_LEVEL=${AKKA_LOG_LEVEL:-info}
    volumes:
      - ${SAFE_IMPORTS:-./safe/imports}:/imports
      - ${SAFE_PRINCIPAL_KEYS:-./safe/keys}:/principalkeys
